/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fivecards.app;

import com.fivecards.model.*;

public class App {

    public static void main(String[] args) {
        System.out.println("App is reaching");

        Game game = new Game();
        
        Player player = new Player();
        player.setId(1);
        player.setName("Nagaraj");
        
        Player player1 = new Player();
        player1.setId(2);
        player1.setName("System");
        
        game.addPlayer(player);
        game.addPlayer(player1);
        
        game.startGame();
        game.showPlayerCards();
        
        System.out.println(game.getDeck().getCards().size());
    }
}
