/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fivecards.app;

import com.fivecards.model.*;

public class App {

    public static void main(String[] args) {
        System.out.println("App is reaching");

        Deck deck = new Deck();
        deck.prepareDeck();
        deck.shuffleCards();
        deck.showDeck();
    }
}
